services:
  - type: web
    name: cambialope
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cambialope-db
          property: connectionString

databases:
  - name: cambialope-db
    databaseName: cambialope
    user: cambialope_user
    plan: free
