"""Add is_draft field to Product model

Revision ID: 18427f32103a
Revises: 68801a8d7655
Create Date: 2025-11-28 08:41:44.906954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18427f32103a'
down_revision = '68801a8d7655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
